#!/usr/bin/env python3
"""
===============================================================================
Global License Manager - Error Handler Utility
===============================================================================
Author:         Vicky Dhale
Created:        2024-01-15
Description:    Centralized error handling for the application
===============================================================================
"""

import sys
import traceback
import logging
from typing import Optional, Tuple
from datetime import datetime

__author__ = "Vicky Dhale"

class ErrorHandler:
    """
    Centralized error handling class
    Developed by Vicky Dhale
    """
    
    def __init__(self):
        self.logger = logging.getLogger(__name__)
        self.error_log = []
        
    def handle(self, error: Exception, context: Optional[str] = None) -> Tuple[bool, str]:
        """
        Handle an exception gracefully
        
        Args:
            error: The exception to handle
            context: Additional context about where the error occurred
            
        Returns:
            Tuple[bool, str]: (can_continue, user_message)
        """
        # Get error details
        error_type = type(error).__name__
        error_msg = str(error)
        trace = traceback.format_exc()
        
        # Log the error
        self.logger.error(f"Error Type: {error_type}")
        self.logger.error(f"Error Message: {error_msg}")
        if context:
            self.logger.error(f"Context: {context}")
        self.logger.debug(f"Traceback:\n{trace}")
        
        # Store in memory
        self.error_log.append({
            'timestamp': datetime.now().isoformat(),
            'type': error_type,
            'message': error_msg,
            'context': context,
            'traceback': trace
        })
        
        # Determine if we can continue
        can_continue = self._can_continue(error)
        
        # Get user-friendly message
        user_msg = self._get_user_message(error)
        
        return can_continue, user_msg
    
    def _can_continue(self, error: Exception) -> bool:
        """Determine if the application can continue after this error"""
        
        # Critical errors - cannot continue
        critical_errors = [
            'MemoryError',
            'SystemError',
            'KeyboardInterrupt',
            'PermissionError'
        ]
        
        error_type = type(error).__name__
        
        if error_type in critical_errors:
            return False
            
        # By default, try to continue
        return True
    
    def _get_user_message(self, error: Exception) -> str:
        """Get user-friendly error message"""
        
        error_type = type(error).__name__
        error_msg = str(error)
        
        # Common error messages
        messages = {
            'FileNotFoundError': "Required file not found. Please check your installation.",
            'PermissionError': "Administrator privileges required. Please run as administrator.",
            'ConnectionError': "Network connection failed. Please check your internet connection.",
            'TimeoutError': "Operation timed out. Please try again.",
            'ModuleNotFoundError': f"Missing module: {error_msg}. Please install required dependencies.",
            'ImportError': "Failed to import required module. Please check your installation."
        }
        
        if error_type in messages:
            return messages[error_type]
        else:
            return f"An error occurred: {error_msg}"
    
    def get_error_log(self) -> list:
        """Get the error log"""
        return self.error_log
    
    def clear_error_log(self):
        """Clear the error log"""
        self.error_log.clear()
        
    def save_error_log(self, filename: str = "error_log.txt"):
        """Save error log to file"""
        try:
            with open(filename, 'w', encoding='utf-8') as f:
                f.write("=" * 60 + "\n")
                f.write("Global License Manager - Error Log\n")
                f.write(f"Generated by: Vicky Dhale\n")
                f.write(f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
                f.write("=" * 60 + "\n\n")
                
                for i, error in enumerate(self.error_log, 1):
                    f.write(f"Error #{i}\n")
                    f.write(f"Timestamp: {error['timestamp']}\n")
                    f.write(f"Type: {error['type']}\n")
                    f.write(f"Message: {error['message']}\n")
                    if error['context']:
                        f.write(f"Context: {error['context']}\n")
                    f.write("-" * 40 + "\n")
                    
            return True
        except Exception as e:
            self.logger.error(f"Failed to save error log: {e}")
            return False

class CriticalError(Exception):
    """Custom exception for critical errors"""
    pass

class ConfigurationError(Exception):
    """Custom exception for configuration errors"""
    pass

class ActivationError(Exception):
    """Custom exception for activation failures"""
    pass